FROM php:8.2-cli

ARG USER=appuser
ARG UID=1000
RUN useradd -u $UID -m $USER

RUN apt-get update && apt-get install -y \
    libpq-dev \
    postgresql-client \
    unzip \
    git \
    libzip-dev \
    libicu-dev \
    && docker-php-ext-install pdo pdo_pgsql pgsql zip intl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .
RUN rm -f .env

RUN chown -R $USER:$USER /var/www

# ✅ Copy entrypoint dengan permission eksekusi langsung
COPY --chmod=755 docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

USER $USER

RUN composer install --no-interaction --prefer-dist --optimize-autoloader

EXPOSE 8000
ENTRYPOINT ["bash", "/usr/local/bin/docker-entrypoint.sh"]
