# Base Jenkins LTS
FROM jenkins/jenkins:lts

USER root

# Install Docker CLI & tools + PHP + ekstensi penting untuk Laravel
RUN apt-get update && \
    apt-get install -y \
        docker.io \
        curl \
        git \
        unzip \
        php-cli \
        php-intl \
        php-xml \
        php-dom \
        php-mbstring \
        php-curl \
        php-zip \
        php-pgsql \
        libpq-dev && \
    apt-get clean

# Install Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/v2.22.2/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# Install Composer (buat Laravel dependencies)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Samakan GID docker group di container dengan host
ARG DOCKER_GID=1001
RUN if getent group docker; then \
      groupmod -g ${DOCKER_GID} docker; \
    else \
      groupadd -g ${DOCKER_GID} docker; \
    fi && \
    usermod -aG docker jenkins

# Balik ke user jenkins (lebih aman)
USER jenkins
